const { Builder, By, until, Key } = require("selenium-webdriver");

async function dynamicid() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click the button
  await driver
    .findElement(By.xpath("/html/body/section[2]/div/div[1]/div[1]/h3/a"))
    .click();

  await driver.findElement(By.xpath("/html/body/section/div/button")).click();

  await driver.quit();
}

async function classattribute() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click the button
  await driver
    .findElement(By.xpath("/html/body/section[2]/div/div[1]/div[2]/h3/a"))
    .click();

  //Find primary-btn
  await driver
    .findElement(
      By.xpath(
        "//button[contains(concat(' ', normalize-space(@class), ' '), ' btn-primary ')]"
      )
    )
    .click();

  //Accepting alert
  let alert = await driver.switchTo().alert();
  await alert.accept();
}

async function hiddenLayers() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click the button
  await driver
    .findElement(By.xpath("/html/body/section[2]/div/div[1]/div[3]/h3/a"))
    .click();

  await driver.sleep(2000);
  //Click green button
  await driver.findElement(By.xpath('//*[@id="greenButton"]')).click();
  await driver.sleep(1000);
  //Click blue button
  await driver.findElement(By.xpath('//*[@id="blueButton"]')).click();
  await driver.sleep(1000);
  //Click green button again - error
  await driver.findElement(By.xpath('//*[@id="greenButton"]')).click();
}

async function loadDelay() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click button Load Delay
  await driver
    .findElement(By.xpath('//*[@id="overview"]/div/div[1]/div[4]/h3/a'))
    .click();

  //Click the button when page is loaded and element located
  await driver
    .wait(until.elementLocated(By.xpath("/html/body/section/div/button")))
    .click();
}

async function ajaxData() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click button Load Delay
  await driver
    .findElement(By.xpath('//*[@id="overview"]/div/div[2]/div[1]/h3/a'))
    .click();

  //Click button triggering ajax request
  await driver.findElement(By.id("ajaxButton")).click();

  //
  await driver
    .wait(until.elementLocated(By.xpath('//*[@id="content"]/p[1]')))
    .click();

  //Click button triggering ajax request
  await driver.findElement(By.id("ajaxButton")).click();

  await driver
    .wait(until.elementLocated(By.xpath('//*[@id="content"]/p[2]')))
    .click();
  await driver.quit();
}

async function waitForScript() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click button Load Delay
  await driver
    .findElement(By.xpath("//*[@id='overview']/div/div[2]/div[2]/h3/a"))
    .click();

  //Click button triggering ajax request
  await driver.findElement(By.id("ajaxButton")).click();

  //Click on the text generated by script
  await driver
    .wait(until.elementLocated(By.xpath('//*[@id="content"]/p')))
    .click();

  await driver.quit();
}

async function click() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click button Load Delay
  await driver
    .findElement(By.xpath("//*[@id='overview']/div/div[2]/div[3]/h3/a"))
    .click();

  //Click on the bad Button
  await driver.findElement(By.id("badButton")).click();
}

async function textInput() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click button Load Delay
  await driver
    .findElement(By.xpath("//*[@id='overview']/div/div[2]/div[4]/h3/a"))
    .click();

  //Entering the text
  await driver
    .findElement(By.id("newButtonName"))
    .sendKeys(Key.NUMPAD1, Key.NUMPAD1, Key.SPACE, Key.NUMPAD1);

  //Click the button
  await driver.findElement(By.xpath('//*[@id="updatingButton"]')).click();
}

async function hideButton() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click button Load Delay
  await driver
    .findElement(By.xpath('//*[@id="overview"]/div/div[3]/div[1]/h3/a'))
    .click();

  await driver.findElement(By.xpath('//*[@id="hidingButton"]')).click();
}

async function dynamicTable() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click button Load Delay
  await driver
    .findElement(By.xpath('//*[@id="overview"]/div/div[3]/div[2]/h3/a'))
    .click();
  //Storing our cpu of chrome
  var chromeCPU = await driver
    .findElement(By.xpath("/html/body/section/div/p[2]"))
    .getText();
  let arrChr = chromeCPU.split(" ");
  console.log(arrChr[2]);

  //   let x = await driver.findElement(By.xpath("")).getText();
  //   console.log(x);
}

async function verifyText() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //click on verify link
  await driver
    .findElement(By.xpath('//*[@id="overview"]/div/div[3]/div[3]/h3/a'))
    .click();

  //finding an element with text (Welcome ...)
  await driver
    .findElement(By.xpath('//span[normalize-space(.)="Welcome UserName!"]'))
    .getText()
    .then((e) => {
      console.log(e);
    });
}

async function progressBar() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //click on progressbar link
  await driver
    .findElement(By.xpath('//*[@id="overview"]/div/div[3]/div[4]/h3/a'))
    .click();

  //finding start button
  await driver.findElement(By.xpath('//*[@id="startButton"]')).click();
  //Find progress bar and save it in variable
  let progressB = await driver.findElement(By.xpath('//*[@id="progressBar"]'));
  //Use our variable inside the function elementTextIs with wait.until construction
  await driver
    .wait(until.elementTextIs(progressB, "75%"))
    .findElement(By.xpath('//*[@id="stopButton"]'))
    .click();
}

async function visibility() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //click on visibility link
  await driver
    .findElement(By.xpath('//*[@id="overview"]/div/div[4]/div[1]/h3/a'))
    .click();

  //Learn locators of all buttons
  await driver.findElement(By.xpath('//*[@id="hideButton"]')).click();

  let removedButton = await driver.findElement(
    By.xpath('//*[@id="removedButton"]')
  );

  let zerowidthButton = await driver.findElement(
    By.xpath('//*[@id="zeroWidthButton"]')
  );

  let transparentButton = await driver.findElement(
    By.xpath('//*[@id="transparentButton"]')
  );

  let invisbleButton = await driver.findElement(
    By.xpath('//*[@id="invisibleButton"]')
  );

  let notdisplayedButton = await driver.findElement(
    By.xpath('//*[@id="notdisplayedButton"]')
  );

  let offscreenButton = await driver.findElement(
    By.xpath('//*[@id="offscreenButton"]')
  );

  let overlappedButton = await driver.findElement(
    By.xpath('//*[@id="overlappedButton"]')
  );

  //We need to understand that if and only if element was removed from DOM, we will not have an option to find it in DOM.
  //We can use different ways to make our buttons and elements in DOM unvisible for human eye.
  //Some of these exampls we have in this case - zero width/ change class(styled hidden)/display: none/opacity and others...
}

async function logIn() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //click on visibility link
  await driver
    .findElement(By.xpath('//*[@id="overview"]/div/div[4]/div[2]/h3/a'))
    .click();

  //First we need to find an element with dynamic ID , that's why we need to use Full xpath
  await driver
    .findElement(By.xpath("/html/body/section/div/div[2]/div/input"))
    .sendKeys("Logggg123in");

  //Here we have the same situation
  await driver
    .findElement(By.xpath("/html/body/section/div/div[3]/div/input"))
    .sendKeys("pwd");

  //After this we just click on the button
  await driver.findElement(By.xpath('//*[@id="login"]')).click();
}

async function mouseOver() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //click on visibility link
  await driver
    .findElement(By.xpath('//*[@id="overview"]/div/div[4]/div[3]/h3/a'))
    .click();

  //Click me - 2 times
  await driver.findElement(By.xpath("/html/body/section/div/div[1]/a")).click();
  await driver.findElement(By.xpath("/html/body/section/div/div[1]/a")).click();
}

async function nonBreakingSpace() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //click on visibility link
  await driver
    .findElement(By.xpath('//*[@id="overview"]/div/div[4]/div[4]/h3/a'))
    .click();
  //changing the space between My and Button to \u00A0, that's how we can find this element in DOM
  await driver
    .findElement(By.xpath("//button[text()='My\u00A0Button']"))
    .click();
}
