const { Builder, By, until, Key } = require("selenium-webdriver");

async function dynamicid() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click the button
  await driver
    .findElement(By.xpath("/html/body/section[2]/div/div[1]/div[1]/h3/a"))
    .click();

  await driver.findElement(By.xpath("/html/body/section/div/button")).click();

  await driver.quit();
}

async function classattribute() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click the button
  await driver
    .findElement(By.xpath("/html/body/section[2]/div/div[1]/div[2]/h3/a"))
    .click();

  //Find primary-btn
  await driver
    .findElement(
      By.xpath(
        "//button[contains(concat(' ', normalize-space(@class), ' '), ' btn-primary ')]"
      )
    )
    .click();

  //Accepting alert
  let alert = await driver.switchTo().alert();
  await alert.accept();
}

async function hiddenLayers() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click the button
  await driver
    .findElement(By.xpath("/html/body/section[2]/div/div[1]/div[3]/h3/a"))
    .click();

  await driver.sleep(2000);
  //Click green button
  await driver.findElement(By.xpath('//*[@id="greenButton"]')).click();
  await driver.sleep(1000);
  //Click blue button
  await driver.findElement(By.xpath('//*[@id="blueButton"]')).click();
  await driver.sleep(1000);
  //Click green button again - error
  await driver.findElement(By.xpath('//*[@id="greenButton"]')).click();
}

async function loadDelay() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click button Load Delay
  await driver
    .findElement(By.xpath('//*[@id="overview"]/div/div[1]/div[4]/h3/a'))
    .click();

  //Click the button when page is loaded and element located
  await driver
    .wait(until.elementLocated(By.xpath("/html/body/section/div/button")))
    .click();
}

async function ajaxData() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click button Load Delay
  await driver
    .findElement(By.xpath('//*[@id="overview"]/div/div[2]/div[1]/h3/a'))
    .click();

  //Click button triggering ajax request
  await driver.findElement(By.id("ajaxButton")).click();

  //
  await driver
    .wait(until.elementLocated(By.xpath('//*[@id="content"]/p[1]')))
    .click();

  //Click button triggering ajax request
  await driver.findElement(By.id("ajaxButton")).click();

  await driver
    .wait(until.elementLocated(By.xpath('//*[@id="content"]/p[2]')))
    .click();
  await driver.quit();
}

async function waitForScript() {
  //launch the browser
  let driver = await new Builder().forBrowser("chrome").build();

  //navigate to our page
  await driver.get("http://uitestingplayground.com/");

  //Click button Load Delay
  await driver
    .findElement(By.xpath("//*[@id='overview']/div/div[2]/div[2]/h3/a"))
    .click();

  //Click button triggering ajax request
  await driver.findElement(By.id("ajaxButton")).click();

  //Click on the text generated by script
  await driver
    .wait(until.elementLocated(By.xpath('//*[@id="content"]/p')))
    .click();

  await driver.quit();
}
waitForScript();
